### ISSUE TITLE
Add Subscribe shortcuts (the purple and Green banner)

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#61]
Same as how it is applied now on IOS (the font, the colors purple and green) 
[https://github.com/EmanHylooz/Abjjad/issues/12](url)

**Comment by EmanHylooz** [comment]
1. The banner did not turn into green after subscription (it remained purple) 
2. Make sure for the green one and purple one to implement the correct font type and size as in IOS. (the purple is different than the green in terms of font type)

**Comment by MahmoudAlyIbrahim** [comment]
done

**Comment by EmanHylooz** [comment]
1. The text inside the purple and green banner is not vertically aligned. 

2. The banner seems to stick sometimes to a certain status. Try this scenario: 
- sign in through you@gmail.com/123456 (unsubscribed user, purple banner shows)
- Sign out, then sign in through eman5@gmail.com/123456 (subscribed user) 
- The purple banner still shows although he is subscribed.

**Comment by Shimaa-Hassan** [comment]
The banner seems to stick sometimes to a certain status. "done"

**Comment by Shimaa-Hassan** [comment]
https://github.com/EmanHylooz/Abjjad/issues/84
